### ISSUE TITLE
Should we train the prior model with n_cond_frames>=1 for BAIR Pushing dataset? 

### ISSUE THREAD

**Issue by xinbowu2** [wilson1yan/VideoGPT#12]
I noticed the generated samples shown on the paper for BAIR Pushing dataset are conditioned on a single frame, so I am wondering if we should also train the prior model conditioning on a single frame. However, I saw the default setting for  n_cond_frames is 0 for BAIR Pushing dataset from another repo: VideoGPT-Paper. Also, I'd like to know if the comparison with other methods on BAIR Pushing Dataset is also based on single-frame conditioning.

**Comment by wilson1yan** [comment]
Yes, for purposes of fair comparisons with prior work, you should train with `--n_cond_frames 1`. All tables / results in the paper related to BAIR are under the single-conditional setting.
