### ISSUE TITLE
shiftdim instead of torch.movedim

### ISSUE THREAD

**Issue by FrancoisPgm** [wilson1yan/VideoGPT#13]
https://github.com/wilson1yan/VideoGPT/blob/a259612b65a5de18c7d720b6e5f0c74e68338179/videogpt/utils.py#L3
In utils you define a shiftdim function that seems to do the same as [torch.movedim](https://pytorch.org/docs/stable/generated/torch.movedim.html). Is there a reason for re-implementing it ?

**Comment by wilson1yan** [comment]
I didn't know that `torch.movedim` existed. I guess I'll be using that in the future :)
