### ISSUE TITLE
AssertionError: Must set max_steps argument

### ISSUE THREAD

**Issue by slerman12** [wilson1yan/VideoGPT#19]
I am getting this error when I try to run the following:

`python3 train_videogpt.py --vqvae ucf101_stride4x4x4 --data_path ./datasets/ucf101/ --gpus 4`

According to the docs, max steps is disabled by default? I'm confused, do I need to pass in a value for it? What would be a good value for achieving convergence on the model?

Thanks. Looking forward to getting this model up and running.

**Comment by wilson1yan** [comment]
Yes, you should pass a value in for it. I believe I ran it with `--max_steps 200000`

**Comment by slerman12** [comment]
Thanks!
