### ISSUE TITLE
setting attribute 

### ISSUE THREAD

**Issue by woanderer** [wilson1yan/VideoGPT#20]
I am having an issue with trying to train the vqvae. 

'''
  File "scripts/train_vqvae.py", line 45, in <module>
    main()
  File "scripts/train_vqvae.py", line 26, in main
    data = VideoData(args)
  File "./videogpt/data.py", line 173, in __init__
    self.hparams = args
AttributeError: can't set attribute
'''

**Comment by wilson1yan** [comment]
I just pushed a change that renames `hparams` to `args` which I think should fix it. Does it work for you now?

**Comment by woanderer** [comment]
> I just pushed a change that renames `hparams` to `args` which I think should fix it. Does it work for you now?

Thanks so much. Great work btw.
