### ISSUE TITLE
Issues about the python version

### ISSUE THREAD

**Issue by baiyuting** [wilson1yan/VideoGPT#27]
the python version I use is 3.6.13,  when I ran "pip install git+https://github.com/wilson1yan/VideoGPT.git", I found  "p~=0.8.1" in the requirements.txt can not be installed.
could you tell me the need python version to run the code ?

**Comment by baiyuting** [comment]
"torchtext~=0.8.1"

**Comment by wilson1yan** [comment]
I used python 3.7, but the installation process seemed to work fine for me with python 3.6.13 as well.

[torchtext 0.8.1](https://pypi.org/project/torchtext/) also seems to support python 3.6

**Comment by baiyuting** [comment]
ok, maybe there are some compatibility problems between torchtext 0.8.1 and windows , https://github.com/pytorch/text/issues/1379 .
I think I may try a lower version of the torchtext and see what it will happen.
