### ISSUE TITLE
Getting "UnpicklingError: invalid load key, '<'." while downloadfing pretrained weights

### ISSUE THREAD

**Issue by Chetan-O6** [wilson1yan/VideoGPT#30]
Hi
I was trying to run the colab version of your project, but under **Downloading a Pretrained VQ-VAE** section I am getting following error. 

![image](https://user-images.githubusercontent.com/86142805/156303528-a2a79507-978e-47c6-8c2e-6547c6381afa.png)

**Comment by wilson1yan** [comment]
It should be working now. Looks like google drive / colab updated some things and the issue should be fixed now

**Comment by Chetan-O6** [comment]
Okay thanks. By the way I downloaded the models and placed them in the specified location and it worked.
