### ISSUE TITLE
deepspeed version

### ISSUE THREAD

**Issue by yrcong** [wilson1yan/VideoGPT#33]
Dear authors,

which version of deepspeed have you used? I am using deepspeed = 0.5.10 and get error with
```from deepspeed.ops.sparse_attention import MatMul, Softmax``` 

I import the module with  ```from deepspeed.ops.sparse_attention.matmul import MatMul```. However, IndexError happens in the forward. 

best

**Comment by wilson1yan** [comment]
Hi,

Perhaps #14 might be of help?

**Comment by yrcong** [comment]
Thx for the reply. I upgrade Triton version and it works:)
