### ISSUE TITLE
The Torch version is a problem when running in Colab.

### ISSUE THREAD

**Issue by LuthandoMaqondo** [wilson1yan/VideoGPT#38]
Can someone help in resolving the issue.

**The commands:** 
`! pip install git+https://github.com/wilson1yan/VideoGPT.gi `
`! pip install scikit-video av`

**_Give me the following output (with an error):_** 
`ERROR: Could not find a version that satisfies the requirement torch~=1.7.1 (from videogpt) (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)`
`ERROR: No matching distribution found for torch~=1.7.1`

**_Full output:_**
<img width="1324" alt="Screenshot 2023-10-03 at 09 00 08" src="https://github.com/wilson1yan/VideoGPT/assets/31970758/63205d2f-b651-4e72-8f73-35763158e34a">
Collecting git+https://github.com/wilson1yan/VideoGPT.git
  Cloning https://github.com/wilson1yan/VideoGPT.git to /tmp/pip-req-build-1js2xdda
  Running command git clone --filter=blob:none --quiet https://github.com/wilson1yan/VideoGPT.git /tmp/pip-req-build-1js2xdda
  Resolved https://github.com/wilson1yan/VideoGPT.git to commit 733d2b1541e166d7f29df514c7d196c768011dd2
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from VideoGPT==1.0) (4.66.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from VideoGPT==1.0) (2.31.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from VideoGPT==1.0) (3.9.0)
INFO: pip is looking at multiple versions of videogpt to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch~=1.7.1 (from videogpt) (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch~=1.7.1
Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11)
Requirement already satisfied: av in /usr/local/lib/python3.10/dist-packages (10.0.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.2)

**Comment by IntelliNik** [comment]
I have a similar problem here, but for a local installation. The installation fails with Python version 3.6 and 3.9. Am I using an incorrect Python version?
