### ISSUE TITLE
transformer training details

### ISSUE THREAD

**Issue by Goulustis** [wilson1yan/VideoGPT#7]
Hi, I was wondering if the "EMA codebook update" of the vqvae should be runned when training the transformer? (specifically, should line 178-198 in vqvae.py be running when training the transformer?)

Thanks in advance.

**Comment by wilson1yan** [comment]
Thanks for bringing my attention to this! The VQ-VAE should not be updating the codebook (or anything for that matter) when the transformer is training.

This seems to stem from it being set to `training = True` during `gpt.train()` calls in pytorch lightning runners. This seems to also cause the codebook to re-init itself which it should not be doing. 

I just committed a [fix](https://github.com/wilson1yan/VideoGPT/commit/b234b809d83db45b0c9076b24ed5d26257031fbf) on master to address this issue, essentially just calling `self.vqvae.eval()` before every training step.
