### ISSUE TITLE
hdf5 file for bair robot dataset

### ISSUE THREAD

**Issue by Gabriel-Huang** [wilson1yan/VideoGPT#9]
Hi, I'm wondering if the hdf5 for bair robot dataset is available for download.

I've tried the create_bair_dataset.sh script from the VideoGPT-Paper repo, but it seems the formatting is different from what you have in this repo? For example, the HDF5Dataset in this repo uses 'train_data' and 'train_idx' to access the data, but create_bair_dataset doesn't seem to create them?

Any help would be appreciated!

**Comment by wilson1yan** [comment]
I've committed a modified version of `create_bair_dataset.sh` in  the `scripts/preprocess/bair` folder. It can be currently found on the `dev` branch (`master` will be updated as soon as I finish some other things). You should be able to generate the `bair.hdf5` file through the following command:

```
sh scripts/preprocess/bair/create_bair_dataset.sh datasets/bair
```

**Comment by Gabriel-Huang** [comment]
thanks a lot!
